/**
 * Exercise3.java Write a method that creates and initializes a two dimensional
 * array of double. The size of the array is determined by the arguments of the 
 * method, and the initialization values are a range determined by beginning and 
 * ending values that are also arguments of the method. Create a second method 
 * that will print the array generated by the first method. In main( ) test the 
 * methods by creating and printing several different sizes of arrays.  
 *
 * @since %I%, %G%
 *
 * @author Kim Nguyen
 */

package kim.nguyen.arrays;

import java.util.Arrays;
import java.util.Random;

/**
 * The Exercise3 class demonstrates how the two dimensional are initialized
 */
public class Exercise3 {
    
	public static void main(String[] args) {
		printValues(iniTwoDArray(5, 3, 10));
	}

	/**
	 * Creates and initializes the two dimensional array of double
	 * 
	 * @param size
	 *            the size of the array
	 * @param beginValue
	 *            the upper edge of the range of the values
	 * @param endValue
	 *            the lower edge of the range of the values
	 * @return the two dimensional array of double
	 */
	public static double[][] iniTwoDArray(int size, int beginValue, int endValue) {

		/* Creates a two dimensional array of double */
		double[][] twoDArray = new double[size][size];

		Random rand = new Random();

		/* Assigns values for the array */
		for (int row = 0; row < size; ++row) {
			for (int column = 0; column < size; ++column) {
					twoDArray[row][column] = rand.nextInt((endValue - beginValue) + 1) + beginValue;
			}
		}

		return twoDArray;
	}

	/**
	 * Prints the two dimensional array
	 * 
	 * @param array
	 *            the two dimensional array in which values will be printed
	 */
	public static void printValues(double[][] array) {
		System.out.println(Arrays.deepToString(array));
	}
}